application: info-cascade 
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static/js
  static_dir: application/static/js

- url: .*
  script: main.py
